apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wooless
spec:
  selector:
    matchLabels:
      app: wooless
      tier: frontend
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: wooless
        tier: frontend
    spec:
      containers:
      - name: wooless
        image:  romiafrizal/wooless-python:latest

---
apiVersion: v1
kind: Service
metadata:
  name: wooless
spec:
  selector:
    app: wooless
    tier: frontend
  type: LoadBalancer # NodePort | ClusterIP  | LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80